image: docker:20.10.16
services:
  - docker:20.10.16-dind

stages:
  - build
  - test
  - release

variables:
  TEST_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  RELEASE_TAG: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $TEST_TAG .
    - docker push $TEST_TAG

test:
  stage: test
  script:
    - docker run $TEST_TAG echo "hello world"

release-image:
  stage: release
  script:
    - docker pull $TEST_TAG
    - docker tag $TEST_TAG $RELEASE_TAG
    - docker push $RELEASE_TAG
  only: 
  - master
